# Generated by Django 4.0.5 on 2022-06-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='profiles_api.task'),
        ),
    ]
