# Generated by Django 4.0.5 on 2022-06-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_userprofile_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tasks',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
